### PR TITLE
[INTERFACES] Add interface for TestUtility plugin; add generated prox…

### PR DESCRIPTION
**Pull request by artur-gebicz-ml**
…y/stubs

Proxy/stubs for TestUtility plugin are generated using ProxyStubs
generator

### CODE REVIEW

**Comment by pwielders** [comment]
Oke from my perspective

**Comment by pwielders** [comment]
Sorry wrong button :-)

**Comment by woutermeek** [comment]
@artur-gebicz-ml could you please fix the conflicting files, so we can merge.

**Comment by artur-gebicz-ml** [comment]
@woutermeek Fixed. Should now be ok (or at least for few minutes :o)

**Pull request merged**
